/**
 * Hard-coded map of deprecation flag name to the version it was introduced.
 * Source of truth: @ember-data/private-build-infra/virtual-packages/deprecations.js
 */
export const DEPRECATION_VERSIONS: Record<string, string> = {
  DEPRECATE_CATCH_ALL: '99.0',
  DEPRECATE_3_12: '3.12',
  DEPRECATE_RSVP_PROMISE: '4.4',
  DEPRECATE_SAVE_PROMISE_ACCESS: '4.4',
  DEPRECATE_SNAPSHOT_MODEL_CLASS_ACCESS: '4.5',
  DEPRECATE_STORE_FIND: '4.5',
  DEPRECATE_HAS_RECORD: '4.5',
  DEPRECATE_STRING_ARG_SCHEMAS: '4.5',
  DEPRECATE_JSON_API_FALLBACK: '4.5',
  DEPRECATE_MODEL_REOPEN: '4.7',
  DEPRECATE_EARLY_STATIC: '4.7',
  DEPRECATE_HELPERS: '4.7',
  DEPRECATE_PROMISE_MANY_ARRAY_BEHAVIORS: '4.7',
  DEPRECATE_V1CACHE_STORE_APIS: '4.7',
  DEPRECATE_RELATIONSHIPS_WITHOUT_TYPE: '4.7',
  DEPRECATE_RELATIONSHIPS_WITHOUT_ASYNC: '4.7',
  DEPRECATE_RELATIONSHIPS_WITHOUT_INVERSE: '4.7',
  DEPRECATE_A_USAGE: '4.7',
  DEPRECATE_PROMISE_PROXIES: '4.7',
  DEPRECATE_ARRAY_LIKE: '4.7',
  DEPRECATE_COMPUTED_CHAINS: '5.0',
  DEPRECATE_NON_EXPLICIT_POLYMORPHISM: '4.7',
  DEPRECATE_V1_RECORD_DATA: '4.12',
  DEPRECATE_INSTANTIATE_RECORD_ARGS: '4.12',
};
